name: coffee_dashboard
description: "A new Flutter project."


publish_to: 'none' 



version: 1.0.0+1


environment:
  sdk: '>=3.4.4 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
 


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

 

  flutter_lints: ^3.0.0




flutter:

  

  uses-material-design: true

  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  
  fonts:
     - family: Teko
       fonts:
         - asset: assets/font/Teko-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
 